---
title: "Figure 1"
author: "Rebecca Hoyd"
date: "1/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggtext)
tar_load(integrated_TCGA_PCAWG)
tar_load(plotdat_scores_for_lm)
tar_load(mitoscores)
```

# A

```{r}
mitoscores %>%
  ggplot(aes(x = BUFFA_HYPOXIA_SCORE, y = AvgExpr)) +
  geom_point(aes(group = pos), alpha = 0.2, color = "grey") +
  theme_bw() +
  stat_smooth(aes(group = pos), method = "lm", color = "red", lwd = 1.5) +
  labs(x = "Buffa Hypoxia Score",
       y = "mitoscore")
ggsave("figures/scatterplot_buffa-mito_all_split-lm.png",
       height = 3, width = 5)
```

# B

```{r}
plotdat_scores_for_lm %>%
  filter(cancer %in% c("THCA", "PRAD", "LGG", "CESC", "LUSC", "HNSC")) %>%
  mutate(`Buffa Category` = fct_relevel(`Buffa Category`, "LB"),
         signature = ifelse(grepl("Electron", signature), "Mitoscore", signature)) %>%
  ggplot(aes(x = BUFFA_HYPOXIA_SCORE, y = score)) +
  geom_point(color = "grey", alpha = 0.2) +
  geom_smooth(aes(color = signature), method = "lm") +
  facet_wrap(~ `Buffa Category` + cancer) +
  labs(x = "Buffa Hypoxia Score",
       y = "Average Log<sub>2</sub> Expression") +
  scale_color_viridis_d(direction = -1, name = "Signature") +
  theme_bw() +
  theme(axis.title.y = element_markdown(),
        legend.position = "top")
  
ggsave("figures/Fig3_hb-lb_3sigs_lm_facet.png",
       height = 10,
       width = 7.5)
```

# C

```{r}
integrated_TCGA_PCAWG %>%
  ggplot(aes(x = buffa.score, y = log.counts
             # color = is.na(BUFFA_HYPOXIA_SCORE)
             )) +
  facet_wrap(vars(Hugo_Symbol), nrow = 1) +
  geom_point(color = "grey", alpha = 0.2) +
  stat_smooth(method = "lm", color = "red") +
  labs(x = "Buffa hypoxia score", 
       y = expression(paste(Log[2], "(Expression + 1)", sep = ""))) +
  theme_bw()
ggsave("figures/scatterplot_buffa-MIR210-genes_TCGA-pcawg.png",
       height = 3, width = 5)
```