---
title: "change point analysis"
author: "Caroline Wheeler"
date: "1/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggExtra)
library(gt)
library(viridis)
library(ggtext)
library(segmented)
library(broom)

source("00-paths.R")
```

```{r}
x <- data.frame(files = list.files(file.path(paths$box, "data", "many-cancers"), 
                                   full.names = TRUE)) %>%
  filter(grepl("\\.txt", files)) %>%
  filter(grepl("MaxLimitsall", files))
  

mitoscore.files <- x %>%
  filter(grepl("OXPHOS", files))
```

```{r}
readAndFilter <- function(table) {
  read.table(table) %>%
    select(BUFFA_HYPOXIA_SCORE, AvgExpr) %>%
    rownames_to_column("sampleID") %>%
    mutate(cancer = table) %>%
    mutate(cancer = gsub(pattern = ".*LogExpr_(.*)_AverageGene.*", 
                         replacement = "\\1",
                         x = cancer))
           # cancer = toupper(cancer)) 
}
```

```{r}
mitoscore <- lapply(X = mitoscore.files$files, readAndFilter) %>%
  bind_rows() %>%
  filter(cancer != 'kirc')
```

run if you want to average AvgExpr
```{r}
mitoscore <- mitoscore %>%
  select(BUFFA_HYPOXIA_SCORE, AvgExpr) %>%
  group_by(BUFFA_HYPOXIA_SCORE) %>%
  summarise(mean(AvgExpr)) 

colnames(mitoscore) <- c("BUFFA_HYPOXIA_SCORE", "AvgExpr")
```

see data
```{r}
p <- ggplot(mitoscore, aes(x = BUFFA_HYPOXIA_SCORE, y = AvgExpr)) + geom_line() + geom_vline(xintercept = -18, linetype="dashed", color = "red")
p
```

```{r}
my.lm <- lm(AvgExpr ~ BUFFA_HYPOXIA_SCORE, data = mitoscore)
summary(my.lm)
```

```{r}
# have to provide estimates for breakpoints.
# after looking a the data, 
my.seg <- segmented(my.lm, 
                    seg.Z = ~ BUFFA_HYPOXIA_SCORE, 
                    psi = list(BUFFA_HYPOXIA_SCORE = -10))

# When not providing estimates for the breakpoints "psi = NA" can be used.
# The number of breakpoints that will show up is not defined
#my.seg <- segmented(my.lm, 
#                    seg.Z = ~ DistanceMeters, 
#                    psi = NA)

# display the summary
summary(my.seg)
```

```{r}
my.seg$psi
```

## Check segmented results

Create split data
```{r}
split0_less <- mitoscore %>% filter(BUFFA_HYPOXIA_SCORE < 0)
split0_more <- mitoscore %>% filter(BUFFA_HYPOXIA_SCORE > 0)
split_neg16_less <- mitoscore %>% filter(BUFFA_HYPOXIA_SCORE < -16)
split_neg16_more <- mitoscore %>% filter(BUFFA_HYPOXIA_SCORE > -16)

lm_0_less <- lm(AvgExpr ~ BUFFA_HYPOXIA_SCORE, data = split0_less) 
lm_0_more <- lm(AvgExpr ~ BUFFA_HYPOXIA_SCORE, data = split0_more)

lm_neg16_less <- lm(AvgExpr ~ BUFFA_HYPOXIA_SCORE, data = split_neg16_less)
lm_neg16_more <- lm(AvgExpr ~ BUFFA_HYPOXIA_SCORE, data = split_neg16_more)
```


Log likelihoods w/ no breaks, break at -16, and break at 0
The actual log-likelihood value for a given model is mostly meaningless, but it’s useful for comparing two or more models.
```{r}
print("No breaks")
logLik(my.lm)

print("Breakpoint = 0")
logLik(lm_0_less) + logLik(lm_0_more)

print("Breakpoint = -16")
logLik(lm_neg16_less) + logLik(lm_neg16_more)
```

# check all buffa values as breakpoint
```{r}
bp_min <- min(mitoscore$BUFFA_HYPOXIA_SCORE) + 5
bp_max <- max(mitoscore$BUFFA_HYPOXIA_SCORE) - 5

bp_data <- setNames(data.frame(matrix(ncol = 2, nrow = 0)), c("breakpoint", "sum(loglik)"))

for (bp in bp_min:bp_max) {
  split_less <- mitoscore %>% filter(BUFFA_HYPOXIA_SCORE < bp)
  split_more <- mitoscore %>% filter(BUFFA_HYPOXIA_SCORE > bp)
  
  lm_less <- lm(AvgExpr ~ BUFFA_HYPOXIA_SCORE, data = split_less) 
  lm_more <- lm(AvgExpr ~ BUFFA_HYPOXIA_SCORE, data = split_more)
  
  temp <- logLik(lm_less) + logLik(lm_more)
  
  new_row <- c(bp, temp)
  bp_data <- rbind(bp_data, new_row)
}
```

plot all breakpoints
```{r}
colnames(bp_data) <- c("Breakpoint", "sum(logLik)")
p <- ggplot(bp_data, aes(x = Breakpoint, y = bp_data$`sum(logLik)`)) + geom_line() + geom_vline(xintercept = -19, linetype="dashed", color = "red") + geom_text(aes(x=-7, label="MaxLogLik = -19", y=-3800), colour="red",  vjust = -1, text=element_text(size=11)) + geom_smooth()
p
```
