---
title: "CNV analysis buffa"
author: "Caroline Wheeler"
date: '2022-07-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(data.table)
library(ggplot2)
library(ggrepel)
library(purrr)
library(MASS)
library(broom)

source("00-paths.R")
```

read in gene list
```{r}
genes <- read.csv("../data/TableS1_signature-gene-sets.csv") %>%
  select()

  # change select and filter inout based on gene set
  select(WP_ELECTRON_TRANSPORT_CHAIN_OXPHOS_SYSTEM_IN_MITOCHONDRIA) %>%
  filter(WP_ELECTRON_TRANSPORT_CHAIN_OXPHOS_SYSTEM_IN_MITOCHONDRIA != "")

genes <- genes[-1,]

#add mispelled gene to list
genes <- append(genes, c("SDHC", "MIR3607", "ATP5O", "ATP5S", "ATP5J", "ATP5H", "ATP5F1", "ATP5A1", "ATPM","ATP5AL2", "ATP5B", "ATPSB", "ATP5C", "ATP5C1", "ATP5CL1", "ATP5D", "ATP5E", "ATPIF1", "ATP5G", "ATP5G1", "ATP5G2", "ATP5G3", "ATP5I", "ATP5J2", "ATP5L"))
```

read in CNA data and filter to gene set
```{r}
cna_files <- data.frame(files = list.files(file.path(paths$drive, "data", "cna_data"), full.names = TRUE))

read_cna <- function(table){
  read.table(table, header = TRUE, fill = TRUE) %>%
    filter(Hugo_Symbol %in% genes) %>%
    select(-Entrez_Gene_Id) 
}

cna <- lapply(X = cna_files$files, read_cna) %>%
  reduce(full_join, by = "Hugo_Symbol") 
```

read in mitoscore data
```{r}
x <- data.frame(files = list.files(file.path(paths$drive, "data", "many-cancers"), 
                                   full.names = TRUE)) %>%
  filter(grepl("\\.txt", files)) %>%
  filter(grepl("MaxLimitsall", files))
  
mitoscore.files <- x %>%
  filter(grepl("OXPHOS", files))
```

```{r}
readAndFilter <- function(table) {
  read.table(table) %>%
    select(BUFFA_HYPOXIA_SCORE) %>%
    rownames_to_column("sampleID") %>%
    mutate(cancer = table) %>%
    mutate(cancer = gsub(pattern = ".*LogExpr_(.*)_AverageGene.*", 
                         replacement = "\\1",
                         x = cancer))
           # cancer = toupper(cancer)) 
}
```

```{r}
buffa <- lapply(X = mitoscore.files$files, readAndFilter) %>%
  bind_rows() 
```

cna wide -> long
```{r}
cna <- melt(setDT(cna), id.vars = c("Hugo_Symbol"), variable.name = "sampleID")
```

```{r}
cna_buffa <- merge(cna, buffa)
```

```{r}
cna_buffa$value <- factor(cna_buffa$value, levels = c("-2", "-1", "0", "1" , "2"))

cna_buffa %>%
  ggplot(aes(x=value, y=BUFFA_HYPOXIA_SCORE)) +
  geom_boxplot(color="red", fill="orange", alpha=0.2) +
  facet_wrap(~Hugo_Symbol) +
  theme_bw() +
  xlab("CNA") 

ggsave("../figures/CNA_analysis_buffa_boxplot_all_genes.png", dpi = 400, width = 15, height = 20)
```

<!-- check which genes were dropped -->
<!-- ```{r} -->
<!-- cna_genes <- cna_buffa$Hugo_Symbol %>% unique() -->

<!-- print(noquote(setdiff(genes, cna_genes))) -->

<!-- x <- as.data.frame(setdiff(genes, cna_genes)) -->
<!-- ``` -->

## heatmap to compare ##

expr level ~ cna category

# using group by and do
# trouble ascessing elements??
```{r}
models = cna_buffa %>% group_by(Hugo_Symbol) %>% do(m = polr(value ~ BUFFA_HYPOXIA_SCORE, data = ., Hess = TRUE))
```

# for loop 
```{r}
gene <- cna_buffa %>%
  dplyr::select(Hugo_Symbol) %>%
  distinct()

geneNames <- gene$Hugo_Symbol

output <- data.frame(matrix(ncol = 5, nrow = 0))
#provide column names
colnames(output) <- c('Value', 'Std. Error', 't value', 'p value', 'gene')

for (g in geneNames) {
  temp <- cna_buffa %>%
    dplyr::filter(Hugo_Symbol == g)
  
  m = polr(value ~ BUFFA_HYPOXIA_SCORE, data = temp, Hess = TRUE)
  ctable <- coef(summary(m))
  p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
  ctable <- cbind(ctable, "p value" = p)
  
  df <- data.frame(matrix(ncol = 1, nrow = 5))
  colnames(df) <- c("gene")
  df$gene <- as.character(g)
  
  ctable <- cbind(ctable, df)
  
  output <- rbind(output, ctable)
  
}
```

filter to buffa hypoxia score
```{r}
filt_output <- output %>%
  filter(grepl("BUFFA", rownames(output)))

filt_output$test <- ""
```

```{r}
ggplot(filt_output, aes(x=test , y=gene, fill=Value)) +
 geom_tile(color = "black") +
    scale_fill_gradient2(low = "#075AFF",
                       mid = "#FFFFCC",
                       high = "#FF0000") +
  xlab("") +
  ylab("") 

ggsave("../figures/all_cancers_heatmap.png", dev = "png", width = 4, height = 10, dpi = 600)
```
save data 
```{r}
saveRDS(cna_buffa, file ="../data/cna_buffa.rds")
```


