---
title: "Fig3-subset"
author: "Caroline Wheeler"
date: "12/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load required packages
library(tidyverse)
library(gt)
library(ggalt)
library(ggridges)
library(forcats)
library(ggdist)

# Source paths 
source("00-paths.R")
```


```{r}
x <- data.frame(files = list.files( file.path(paths$box, 
                                              "data", 
                                              "many-cancers"), 
                                    full.names = TRUE)) %>%
  filter(grepl("\\.txt", files)) %>%
  filter(grepl("MaxLimitsall", files))

#GOBP_MITOPHAGY included the wrong genes
mitophagy.files <- x %>%
  filter(grepl("GOBP_and_REACTOME_MITOPHAGY", files))

biogen.files <- 
  x %>%
  filter(grepl("BIOGEN", files))

etc.files <- 
  x %>%
  filter(grepl("ELECTRON", files))
```

```{r}
# Define a function to read in all the files and select columns of interest
readAndFilter <- function(table) {
  read.table(table) %>%
    select(BUFFA_HYPOXIA_SCORE, AvgExpr) %>%
    rownames_to_column("sampleID") %>%
    mutate(cancer = table) %>%
    mutate(cancer = gsub(pattern = ".*LogExpr_(.*)_AverageGene.*", 
                         replacement = "\\1",
                         x = cancer))
}

mitophagy <- lapply(X = mitophagy.files$files, readAndFilter) %>%
  bind_rows() %>%
  rename("Mitophagy" = "AvgExpr")

biogen <- lapply(X = biogen.files$files, readAndFilter) %>%
  bind_rows() %>%
  rename("Mitochondrial Biogenesis" = "AvgExpr")

etc <- lapply(X = etc.files$files, readAndFilter) %>%
  bind_rows() %>%
  rename("Electron Transport Chain" = "AvgExpr")

comb <- 
  mitophagy %>%
  full_join(biogen) %>%
  full_join(etc) %>%
  mutate(pos = if_else(BUFFA_HYPOXIA_SCORE > 0,
                      true = "positive",
                      false = "negative"))

dim(comb)
head(comb)
```
There's a concept of low and high mean buffa score cancers. I'll take that at face value for the assignment

```{r}
mean.buffa <- 
  comb %>%
  group_by(cancer) %>%
  summarize(mean = mean(BUFFA_HYPOXIA_SCORE)) %>%
  mutate(`Buffa Category` = if_else(mean > 20,
                             "HB",
                             ifelse(mean < -20, 
                                    "LB",
                                    "Avg."))) %>%
  mutate(cancer = fct_reorder(cancer, mean))

mean.buffa %>%
  gt()
```

```{r}
mean.buffa %>%
  ggplot(aes(x = mean, y = cancer)) +
  geom_segment(aes(y = cancer, yend = cancer, x = mean, xend = 1), size = .8, alpha = .8) +
  geom_point(aes(x = mean, y = cancer, fill = `Buffa Category`), shape = 21, size = 6, alpha = .9) +
  theme_bw() +
  labs(x = "Mean Buffa Score",
       y = "") +
  scale_fill_viridis_d() +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9"))

ggsave("../figures/mean-buffa_lollipop_SUBSET.png",
       height = 4, width = 6)
```

```{r}
mitoGenes <- read.csv("../data/TableS1_signature-gene-sets.csv", skip = 1)
```

```{r}
cmb <- 
  comb %>%
  full_join(mean.buffa) %>%
  mutate(cancer = fct_reorder(cancer, mean))
```

```{r}
cmbl <- 
  cmb %>%
  filter(cmb$`Buffa Category` != "Avg.") %>%
  select(-mean) %>%
  gather(key = "signature", value = "score", 
         -BUFFA_HYPOXIA_SCORE,
         -cancer,
         -pos,
         -`Buffa Category`,
         -sampleID) %>%
  mutate(`Buffa Category` = fct_relevel(`Buffa Category`, "LB"),
         signature = gsub("Electron Transport Chain", "Mitoscore", signature))


head(cmbl)
```


```{r}
cmbl %>%
  ggplot(aes(x = BUFFA_HYPOXIA_SCORE, y = score)) +
  geom_point(color = "grey", alpha = 0.2) +
  geom_smooth(aes(color = signature), method = "lm") +
  facet_wrap(~`Buffa Category`) +
  labs(x = "Buffa Hypoxia Score",
       y = expression(paste("Average ", Log[2], " Expression", sep = ""))) +
  theme_bw() +
  scale_color_viridis_d()
ggsave("../figures/Fig3_hb-lb_3sigs_lm_version2.png",
       height = 4,
       width = 6)
```


```{r}
cmbl %>%
  ggplot(aes(x = BUFFA_HYPOXIA_SCORE, y = score)) +
  geom_point(color = "grey", alpha = 0.2) +
  geom_smooth(aes(color = signature), method = "lm") +
  facet_wrap(~ `Buffa Category` + cancer) +
  labs(x = "Buffa Hypoxia Score",
       y = "Mitochondrial Oxygen Demand") +
  theme_bw() +
  scale_color_viridis_d()
ggsave("../figures/SuppFig2_hb-lb_3sigs_loess_facet_version2.png",
       height = 6,
       width = 7.5)
```


# Raincloud plot

```{r}
comb %>%

  ggplot(aes(x = BUFFA_HYPOXIA_SCORE, y = cancer)) +
  ggdist::stat_halfeye(
    adjust = .5, 
    width = .5, 
    .width = 0, 
    justification = -.3, 
    point_colour = NA) +
  geom_boxplot(
    width = .25, 
    outlier.shape = NA
  ) +
  geom_point(
    size = 1,
    alpha = .3,
    position = position_jitter(
      seed = 1, width = 0.1
    )
  ) +
  theme_bw() 
ggsave("../figures/cancer-buffa_raincloud.png",
       height = 8, width = 7)
  coord_cartesian(xlim = c(1.2, NA), clip = "off")
```

# Notes from https://github.com/z3tt/TidyTuesday/blob/master/R/2020_31_PalmerPenguins.Rmd 

```{r}
rain <- 
  ggplot(df_peng_iqr, aes(bill_ratio, species_num - .2)) +
  geom_rect(
    data = df_rect,
    aes(
      xmin = xmin, xmax = xmax,
      ymin = ymin, ymax = ymax
    ),
    inherit.aes = F,
    fill = "white"
  ) +
  geom_linerange(
    data = df_peng_iqr %>% 
      group_by(species, species_num) %>% 
      summarize(m = unique(median)),
    aes(
      xmin = -Inf, 
      xmax = m, 
      y = species_num,
      color = species
    ),
    inherit.aes = F,
    linetype = "dotted",
    size = .7
  ) +
  geom_boxplot(
    aes(
      color = species,
      color = after_scale(darken(color, .1, space = "HLS"))
    ),
    width = 0,
    size = .9
  ) +
  geom_rect(
    aes(
      xmin = q25,
      xmax = median,
      ymin = species_num - .05,
      ymax = species_num - .35
    ),
    fill = "grey89"
  ) +
  geom_rect(
    aes(
      xmin = q75,
      xmax = median,
      ymin = species_num - .05,
      ymax = species_num - .35
    ),
    fill = "grey79"
  ) +
  geom_segment(
    aes(
      x = q25, 
      xend = q25,
      y = species_num - .05,
      yend = species_num - .35,
      color = species,
      color = after_scale(darken(color, .05, space = "HLS"))
    ),
    size = .25
  ) +
  geom_segment(
    aes(
      x = q75, 
      xend = q75,
      y = species_num - .05,
      yend = species_num - .35,
      color = species,
      color = after_scale(darken(color, .05, space = "HLS"))
    ),
    size = .25
  ) +
  geom_point(
    aes(
      color = species
    ), 
    shape = "|",
    size = 5,
    alpha = .33
  ) +
  ggdist::stat_halfeye(
    aes(
      y = species_num,
      color = species,
      fill = after_scale(lighten(color, .5))
    ),
    shape = 18,
    point_size = 3,
    interval_size = 1.8,
    adjust = .5,
    .width = c(0, 1)
  ) +
  geom_text(
    data = df_peng_iqr %>% 
      group_by(species, species_num) %>% 
      summarize(m = unique(median)),
    aes(
      x = m, 
      y = species_num + .12,
      label = format(round(m, 2), nsmall = 2)
    ),
    inherit.aes = F,
    color = "white",
    family = "Neutraface Slab Display TT Titl",
    size = 3.5
  ) +
  geom_text(
    data = df_peng_iqr %>% 
      group_by(species, species_num) %>% 
      summarize(n = unique(n), max = max(bill_ratio, na.rm = T)),
    aes(
      x = max + .01, 
      y = species_num + .02,
      label = glue::glue("n = {n}"),
      color = species
    ),
    inherit.aes = F,
    family = "Neutraface Slab Display TT Bold",
    size = 3.5,
    hjust = 0
  ) +
  annotation_custom(i2, ymin = 2.5, ymax = 3.6, xmin = 3, xmax = 3.7) +
  coord_cartesian(clip = "off") +
  scale_x_continuous(
    limits = c(1.57, 3.7),
    breaks = seq(1.6, 3.6, by = .2),
    expand = c(.001, .001)
  ) +
  scale_y_continuous(
    limits = c(.55, NA),
    breaks = 1:3,
    labels = c("Gentoo", "Chinstrap", "Adélie"),
    expand = c(0, 0)
  ) +
  scale_color_manual(
    values = pal,
    guide = F
  ) +
  scale_fill_manual(
    values = pal,
    guide = F
  ) +
  labs(
    x = "Bill ratio",
    y = NULL,
    subtitle = "B. Distribution of the bill ratio, estimated as bill length divided by bill depth",
    caption = 'Note: In the original data, bill dimensions are recorded as "culmen length" and "culmen depth". The culmen is the dorsal (upper) ridge of a bird’s bill.\nVisualization: Cédric Scherer  •  Data: Gorman, Williams & Fraser (2014) DOI: 10.1371/journal.pone.0090081  •  Illustrations: Allison Horst'
  ) +
  theme(
    panel.grid.major.y = element_blank(),
    axis.text.y = element_text(family = "Neutraface Slab Display TT Titl", 
                               color = rev(pal), size = 14, lineheight = .9),
    axis.ticks.length = unit(0, "lines"),
    plot.subtitle = element_text(margin = margin(0, 0, -10, 0))
  )
```

