---
title: "LCMC3 buffa mitoscore survival"
author: "Caroline Wheeler"
date: "4/8/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tmesig)
library(ggplot2)
library(survminer)
library(survival)
library(ggsurvfit)
```

```{r input files used}
md5sum(c("/fs/ess/PAS1859/qinma/Genentech/RNA.2023/LCMC3.bulkRNA.lcpm_batch_effect_norm.shareWithOSU.csv",
       "/fs/ess/PAS1859/qinma/Genentech/Clinical.2024/clinical_ATE_biom_2024-04-18_masked_OSU.csv"))
```

read in data 

Notes: unsure about clincial variables used...
using 
"EVNTDESC" - ALive/Dead
ADY" = "Analysis Relative Day"
```{r}
expr <- read.csv("/fs/ess/PAS1859/qinma/Genentech/RNA.2023/LCMC3.bulkRNA.lcpm_batch_effect_norm.shareWithOSU.csv") %>%
  rename("Gene" = X) 

clin <- read.csv("/fs/ess/PAS1859/qinma/Genentech/Clinical.2024/clinical_ATE_biom_2024-04-18_masked_OSU.csv") %>%
  # remove unnecessary PHI
  select("USUBJID2", "EVNTDESC", "ADY", "PARAMCD")
```

<!-- variable check -->
<!-- ```{r} -->
<!-- clin <- clin %>% -->
<!--   mutate(days = as.Date(ADT) - as.Date(ATSDT), -->
<!--          trt.days = as.Date(TRTEDT) - as.Date(TRTSDT)) -->
<!-- ``` -->

filter and match uniq ids to clinical data
```{r}
expr.sx <- expr %>% select(Gene, contains("Sx"))
expr.bl <- expr %>% select(Gene, contains("Bl"))

# will need to change the bounds based on which group of samples you are using 
names(expr.bl)[2:64] <- gsub("_", "-", substring(names(expr.bl)[2:64], 4, 20))
names(expr.sx)[2:54] <- gsub("_", "-", substring(names(expr.sx)[2:54], 4, 20))
```

calculate scores
```{r}
# baseline
buffa <- calculateBuffa(expr.bl, buffa.genes = inputGenes("Buffa"))
mit <- calculateMitoscore(expr.bl, mito.genes = inputGenes("Mitoscore"))

# post trt
# buffa.sx <- calculateBuffa(expr.sx, buffa.genes = inputGenes("Buffa"))
# mit.sx <- calculateMitoscore(expr.sx, mito.genes = inputGenes("Mitoscore"))
```

calculate tertiles
```{r}
buffa.tert <- quantile(buffa$buffa.score, c(0:3/3))
mito.tert <- quantile(mit$MitoScore, c(0:3/3))

buffa$tert <- with(buffa, cut(buffa.score, buffa.tert, include.lowest = T, labels = c("Low Buffa", "Medium Buffa", "High Buffa")))
mit$tert <- with(mit, cut(MitoScore, mito.tert, include.lowest = T, labels = c("Low Mitoscore", "Medium Mitoscore", "High Mitoscore")))
```

combine and prep data 
```{r}
# filter to OS, calc months
clin <- clin %>%
  rename("sample" = USUBJID2) %>%
  mutate("months" = round(ADY/30.417, digit=0),
         "status" = ifelse(EVNTDESC %in% c("Death", "Disease Recurrence","Disease Progression"), 1, 0)) %>%
# can use DFS or OS, specify here  
  filter(PARAMCD == "DFS")

surv.in.buffa <- clin %>%
  left_join(buffa) %>%
  filter(!is.na(buffa.score)) %>%
  mutate(buffa.hi = ifelse(buffa.score > median(buffa.score), "High Buffa", "Low Buffa"))

buffa.t <- surv.in.buffa %>%
  filter(tert != "Medium Buffa")

surv.in.mito <- clin %>%
  left_join(mit) %>%
  filter(!is.na(MitoScore)) %>%
  mutate(mito.hi = ifelse(MitoScore > median(MitoScore), "High Mitoscore", "Low Mitoscore")) 

mito.t <- surv.in.mito %>%
  filter(tert != "Medium Mitoscore")

# surv.in.buffa.sx <- clin %>%
#   left_join(buffa.sx) %>%
#   filter(!is.na(buffa.score)) %>%
#   mutate(buffa.hi = ifelse(buffa.score > median(buffa.score), "High Buffa", "Low Buffa"))
# 
# # post trt
# surv.in.mito.sx <- clin %>%
#   left_join(mit.sx) %>%
#   filter(!is.na(MitoScore)) %>%
#   mutate(mito.hi = ifelse(MitoScore > median(MitoScore), "High Mitoscore", "Low Mitoscore"))
```

## survival analysis

baseline, buffa
```{r}
surv.b <- ggsurvfit::survfit2(Surv(months, status) ~ buffa.hi, data = surv.in.buffa)

surv.b %>%
  ggsurvfit() +
  add_pvalue() +
  add_risktable()

ggsave("../figures/km-curve_LCMC3_buffa.png", height = 5, width = 4)
```

basline, mitoscore
```{r}
surv.m <- ggsurvfit::survfit2(Surv(months, status) ~ mito.hi, data = surv.in.mito)

surv.m %>%
  ggsurvfit() +
  add_pvalue() +
  add_risktable()

ggsave("../figures/km-curve_LCMC3_mito.png", height = 5, width = 4)
```
baseline, tertile, buffa
```{r}
surv.b.t <- ggsurvfit::survfit2(Surv(months, status) ~ tert, data = buffa.t)

surv.b.t %>%
  ggsurvfit() +
  add_pvalue() +
  add_risktable()

ggsave("../figures/km-curve_LCMC3_buffa-tertile.png", height = 5, width = 4)
```

baseline, tertile, mitoscore
```{r}
surv.m.t <- ggsurvfit::survfit2(Surv(months, status) ~ tert, data = mito.t)

surv.m.t %>%
  ggsurvfit() +
  add_pvalue() +
  add_risktable()

ggsave("../figures/km-curve_LCMC3_mito-tertile.png", height = 5, width = 4)
```

<!-- post trt, buffa -->
<!-- ```{r} -->
<!-- surv.b.sx <- ggsurvfit::survfit2(Surv(months, status) ~ buffa.hi, data = surv.in.buffa.sx) -->

<!-- surv.b.sx %>% -->
<!--   ggsurvfit() + -->
<!--   add_pvalue() -->
<!-- ``` -->

<!-- post trt, mitoscore -->
<!-- ```{r} -->
<!-- surv.m.sx <- ggsurvfit::survfit2(Surv(months, status) ~ mito.hi, data = surv.in.mito.sx) -->

<!-- surv.m.sx %>% -->
<!--   ggsurvfit() + -->
<!--   add_pvalue() -->
<!-- ``` -->
