---
title: "LCMC3-immune correlation"
author: "Caroline Wheeler"
date: "4/17/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(tmesig)
library(broom)
library(psych)
```

```{r}
expr <- read.csv("/fs/ess/PAS1859/qinma/Genentech/RNA.2023/LCMC3.bulkRNA.lcpm_batch_effect_norm.shareWithOSU.csv") %>%
  rename("Gene" = X) 

immune <- read.csv("/fs/ess/PAS1859/qinma/Genentech/RNA.2023/LCMC3.bulkRNA.cell_type_enrichment.xCell.shareWithOSU.csv")
```

baseline v. post trt
```{r}
expr.sx <- expr %>% select(Gene, contains("Sx"))
expr.bl <- expr %>% select(Gene, contains("Bl"))
```

calculate scores
```{r}
# baseline
buffa <- calculateBuffa(expr.bl, buffa.genes = inputGenes("Buffa"))
mit <- calculateMitoscore(expr.bl, mito.genes = inputGenes("Mitoscore"))

# post trt
buffa.sx <- calculateBuffa(expr.sx, buffa.genes = inputGenes("Buffa"))
mit.sx <- calculateMitoscore(expr.sx, mito.genes = inputGenes("Mitoscore"))
```

clean up immune cells 
```{r}
immune.bl <- immune %>% 
  select(X, contains("Bl")) %>% 
  column_to_rownames("X") %>%
  t %>%
  as.data.frame %>%
  rownames_to_column("sample")

immune.sx <- immune %>% 
  select(X, contains("Sx")) %>%
  column_to_rownames("X") %>%
  t %>%
  as.data.frame %>%
  rownames_to_column("sample")
```

correlation
```{r}
bl <- immune.bl %>%
  left_join(buffa) %>%
  left_join(mit) %>%
  select(-sample)

bl.corr <- lapply(colnames(bl), function(x) 
    lapply(c("buffa.score", "MitoScore"), function(y) cor.test(bl[[x]], bl[[y]], 
                                            method = "spearman", exact = F) %>%
             tidy() %>%
             mutate(immune.cell = x, score = y) %>%
             bind_rows())) %>%
    bind_rows() %>%
  mutate(p.adj = p.adjust(p.value, method = "fdr"),
         corr = ifelse(p.adj < 0.05, estimate, NA))

sx <- immune.sx %>% 
  left_join(buffa.sx) %>% 
  left_join(mit.sx) %>% 
  select(-sample)

sx.corr <- lapply(colnames(sx), function(x) 
    lapply(c("buffa.score", "MitoScore"), function(y) cor.test(sx[[x]], sx[[y]], 
                                            method = "spearman", exact = F) %>%
             tidy() %>%
             mutate(immune.cell = x, score = y) %>%
             bind_rows())) %>%
    bind_rows() %>%
  mutate(p.adj = p.adjust(p.value, method = "fdr"),
         corr = ifelse(p.adj < 0.05, estimate, NA))
```

<!-- old version w/o p-val  -->
<!-- ```{r} -->
<!-- # baseline -->
<!-- bl <- immune.bl %>% -->
<!--   left_join(buffa) %>% -->
<!--   left_join(mit) %>% -->
<!--   select(-sample) %>% -->
<!--   cor(method = "spearman") %>% -->
<!--   as.data.frame() %>% -->
<!--   rownames_to_column("immune.cell") %>% -->
<!--   gather("score", "corr", -immune.cell) %>% -->
<!--   filter(score %in% c("buffa.score", "MitoScore"), -->
<!--          !immune.cell %in% c("buffa.score", "MitoScore")) -->

<!-- # post trt -->
<!-- sx <- immune.sx %>% -->
<!--   left_join(buffa.sx) %>% -->
<!--   left_join(mit.sx) %>% -->
<!--   select(-sample) %>% -->
<!--   cor(method = "spearman") %>% -->
<!--   as.data.frame() %>% -->
<!--   rownames_to_column("immune.cell") %>% -->
<!--   gather("score", "corr", -immune.cell) %>% -->
<!--   filter(score %in% c("buffa.score", "MitoScore"), -->
<!--          !immune.cell %in% c("buffa.score", "MitoScore")) -->
<!-- ``` -->

baseline plot
```{r}
bl.corr %>%
  ggplot(aes(x=score, y=reorder(immune.cell, corr), fill=corr)) + 
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "#075AFF",
                       mid = "#FFFFCC",
                       high = "#FF0000") +
  coord_fixed() +
  xlab("") + 
  ylab("") +
  theme(axis.text.x = element_text(angle = 60, vjust = 1, hjust = 1),
        aspect.ratio = 10,
        text = element_text(size = 20)) +
  ggtitle("Baseline")

ggsave("../figures/heatmap_LCMC3-baseline.png", height = 25, width = 8)
```

post trt plot
```{r}
sx.corr %>%
  ggplot(aes(x=score, y=reorder(immune.cell, corr), fill=corr)) + 
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "#075AFF",
                       mid = "#FFFFCC",
                       high = "#FF0000") +
  coord_fixed() +
  xlab("") + 
  ylab("") +
  theme(axis.text.x = element_text(angle = 60, vjust = 1, hjust = 1),
        aspect.ratio = 10,
        text = element_text(size = 20)) +
  ggtitle("Post Treatment")

ggsave("../figures/heatmap_LCMC3-post.png", height = 25, width = 8)
```

save correlations in table
```{r}
write.csv(bl.corr, "../data/spearman-corr_LCMC3-baseline.csv", row.names = F)
write.csv(sx.corr, "../data/spearman-corr_LCMC3-post.csv", row.names = F)
```

