---
title: "mir210-corr-with-Buffa"
author: "Dan Spakowicz"
date: "1/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(devtools)
# install_github("spakowiczlab/tmesig")
library(tmesig)
library(forcats)

source("00-paths.R")
```


# Grab and investigate MIR210 data
```{r}
x <- read.table(file = "../data/mRNA expression (FPKM_UQ).txt",
                na = "NA",
                header = TRUE)

head(x)
```

```{r}
y <- 
  x %>%
  filter(!is.na(MIR.210.5P))

dim(y)
```

```{r}
head(y)
```


```{r}
y %>%
  ggplot(aes(x = MIR.210.5P)) +
  geom_histogram() +
  theme_bw()
```


```{r}
summary(y$MIR.210.5P)
```

```{r}
y %>%
  ggplot(aes(x = log(MIR.210.5P+1))) +
  geom_histogram() +
  theme_bw()

ggsave("../figures/mir210-histogram.png",
       height = 3, width = 4)
```

```{r}
table(y$STUDY_ID)
```

# Grab and investigate full gene tables

```{r}
pcawg.files <- list.files(file.path(paths$box, "data", "pancan_pcawg_2020"), 
                          full.names = TRUE)

pcawg.files
```

```{r}
mirna <- read.table(pcawg.files[grep("data_mirna.txt", pcawg.files)],
                    header = TRUE) 

head(mirna)
```


```{r}
pm <- 
  mirna %>%
  gather(-Hugo_Symbol, key = "sampleID", value = "FPKM") %>%
  spread(key = Hugo_Symbol, value = FPKM)

pm %>%
  dplyr::select(contains("mir-210")) %>%
  gather(key = "miR", value = "FPKM") %>%
  ggplot(aes(x = log(FPKM+1))) +
  geom_histogram(aes(fill = miR)) +
  theme_bw() 

ggsave("../figures/pcawg_mir210_histogram.png",
       height = 3, width = 4)
```

```{r}
rna <-
  read.table(pcawg.files[grep("data_mrna_seq_fpkm.txt", pcawg.files)],
                    header = TRUE) 
```

# Use desired tables for correlation

```{r check for samples from KIRC that should be excluded}
clin <- read.table(pcawg.files[grep("data_clinical_sample.txt", pcawg.files)],
                   sep = "\t", header = T)

table(clin$ORGAN_SYSTEM)

clin.possbad <- clin %>%
  filter(ORGAN_SYSTEM == "KIDNEY")

clin.possbad %>%
  mutate(HISTOLOGY = as.character(HISTOLOGY)) %>%
  group_by(HISTOLOGY) %>%
  tally()

badsamps <- clin %>%
  filter(HISTOLOGY_ABBREVIATION %in% c("Kidney-RCC", "Kidney-ChRCC"))
```

```{r calculate buffa score}
checkGenes(as.character(rna$Hugo_Symbol), "Buffa")
alt.gene.names <- c("PNP", "HILPDA", "MRGBP", "AK3", "ESRP1", "CTSV")

buffain <- rna %>%
  mutate(Gene = as.character(Hugo_Symbol)) %>%
  dplyr::select(-Hugo_Symbol) %>%
  dplyr::select(-any_of(badsamps$SAMPLE_ID)) %>%
  dplyr::select(-any_of(clin$SAMPLE_ID[is.na(clin$HISTOLOGY_ABBREVIATION)]))

rna.buffa <- calculateBuffa(buffain, c(inputGenes("Buffa"), alt.gene.names))
```

```{r format for correlation}
corr.in.gene <- rna %>%
  filter(Hugo_Symbol %in% c("PDK1", "PDK3", "NDUFA4L2")) %>%
  gather(!Hugo_Symbol, key = "sample", value = "counts") %>%
  mutate(log.counts = log(counts + 1)) %>%
  dplyr::select(sample, Hugo_Symbol, log.counts) %>%
  left_join(rna.buffa)

corr.in.mir <- mirna %>%
  column_to_rownames(var = "Hugo_Symbol") %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  mutate(log.counts = log(`hsa-miR-210-3p` + 1),
         Hugo_Symbol = "MIR210") %>%
  dplyr::select(sample, Hugo_Symbol, log.counts) %>%
  left_join(rna.buffa)

table(is.na(corr.in.mir$buffa.score))

corr.in <- corr.in.mir %>%
  drop_na(buffa.score)

corr.in <- corr.in.gene %>%
  filter(sample %in% corr.in$sample) %>%
  bind_rows(corr.in)
```

```{r statisitcal correlation test}
stat.in <- corr.in %>%
  spread(key = "Hugo_Symbol", value = "log.counts")
cor.test(stat.in$MIR210, stat.in$buffa.score)

lm(MIR210 ~ buffa.score, data = stat.in) %>%
  summary()
```

```{r plot buffa v genes with facet}
corr.in %>%
  ggplot(aes(x = buffa.score, y = log.counts)) +
  facet_wrap(vars(Hugo_Symbol), nrow = 1) +
  geom_point(color = "grey", alpha = 0.2) +
  stat_smooth(method = "lm", color = "red") +
  labs(x = "Buffa Hypoxia Score", y = "log(expression + 1)") +
  theme_bw() 
ggsave("../figures/scatterplot_buffa-vs-mir210.png",
       height = 3, width = 4)
```

```{r plot buffa v mir210 with cancer facet}
corr.can <- 
  corr.in %>%
  mutate(SAMPLE_ID = sample) %>%
  left_join(clin)

can.ord <- 
  corr.can %>%
  group_by(HISTOLOGY_ABBREVIATION) %>%
  summarize(mean.Buffa = mean(buffa.score)) %>%
  arrange(mean.Buffa)
can.ord.vec <- can.ord$HISTOLOGY_ABBREVIATION

corr.can %>% 
  # left_join(can.ord) %>%
  mutate(HISTOLOGY_ABBREVIATION = fct_relevel(HISTOLOGY_ABBREVIATION,
                                              can.ord.vec)) %>%
  ggplot(aes(x = buffa.score, y = log.counts)) +
  facet_wrap(vars(HISTOLOGY_ABBREVIATION,Hugo_Symbol), ncol = 4) +
  geom_point(color = "grey", alpha = 0.2) +
  stat_smooth(method = "lm", color = "red") +
  labs(x = "Buffa Hypoxia Score", y = "log(expression + 1)") +
  theme_bw() 
ggsave("../figures/scatterplot_buffa-vs-mir210_facet.png",
       height = 30, width = 7.5)
```

```{r write data for combine with TCGA}
export.data <- corr.can %>%
  select(sample, Hugo_Symbol, log.counts, buffa.score, HISTOLOGY_ABBREVIATION)

saveRDS(export.data, "../data/mir210-with-genes.RDS")
```


