---
title: "mt.surv exotho"
author: "C. Dravillas"
date: "2025-04-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(mt.surv)
library(purrr)
library(patchwork)
```


# Get data (n = 403 samples)

```{r}
# scores
scores <- read.csv("../data/tho_lung_cancer-mitoBuffa-TPM.csv")

# clinical info 
pt.key <- read_delim("../data/tho_lung_cancer.s_clinical_data.tsv", delim = "\t", quote = "", col_names = TRUE) %>%
  separate(`Sample ID`, into = c("Pt.id", "sample", "WES.ID"), sep = "_", fill = "right") %>%
  mutate(WES.ID = ifelse(`Sequencing Type` == "WES", sample, WES.ID),
         sample = ifelse(`Sequencing Type` == "WES", NA, sample),
         sample = gsub("-RNA", "", sample)) %>%
  filter(sample %in% scores$sample) %>%
  # get vars of interest 
  select(sample, AgeAtDiagnosis, AgeAtLastContact, PatientVitalStatus, RadiationTherapyInd, ImmunoOncologyDrug) %>%
  full_join(scores)
```
# Create surv var and input data 

```{r}
survin <- pt.key %>%
  mutate(days = (365.25*as.numeric(AgeAtLastContact))-(365.25*as.numeric(AgeAtDiagnosis)),
         vitalstatus = ifelse(PatientVitalStatus == "Dead", 1, 0))

rad <- filter(survin, RadiationTherapyInd == "Yes")
io <- filter(survin, ImmunoOncologyDrug == "Yes")
```
# New function from AL
```{r}
survivalByQuantile <- function(input.var, input.tax, surv.dat, percentiles = seq(.01, .99, 0.01)) {

  aa <- function(input.var, input.tax, surv.dat, percent) {
    surv.dat$input.var <- input.tax[[input.var]]
    cut <- quantile(surv.dat$input.var, percent)

    surv.dat$tmp <- case_when(surv.dat$input.var < cut ~ 0,
                              surv.dat$input.var >= cut ~ 1)
    surv.dat$tmp <- factor(surv.dat$tmp)
    surv.dat$tmp <- forcats::fct_relevel(surv.dat$tmp, "0")

    surv_model <- survival::coxph(survival::Surv(days, vitalstatus) ~ tmp, surv.dat)

    tidy_out <- broom::tidy(surv_model, exponentiate = TRUE, conf.int = TRUE)

    dat_temp <- tidy_out %>%
      dplyr::filter(term == "tmp1") %>%  # keep the comparison group (vs. reference "0")
      dplyr::mutate(
        percentile = percent,
        cutoff.value = cut,
        hazard.direction = ifelse(estimate >= 1, ">=1", "<1")
      ) %>%
      dplyr::select(
        hazard.ratio = estimate,
        low.bound = conf.low,
        upper.bound = conf.high,
        percentile,
        cutoff.value,
        pval = p.value,
        hazard.direction
      )

    return(dat_temp)
  }

  # Run over all percentiles
  results <- purrr::map_dfr(percentiles, ~aa(input.var, input.tax, surv.dat, .x))
  return(results)
}
```
9 mtsurv curves:

3 scores
- mitoscore.tpm
- buffa.tpm
- ndufb5.tpm

3 cohorts
- All
- only those treated with radiation
- only those treated with IO

# mt.surv

Note - function requires same order of samples 

```{r}
# ALL
all.mito <- survivalByQuantile("MitoScore.TPM", survin, survin)
all.buffa <- survivalByQuantile("buffa.score.TPM", survin, survin)
all.nduf <- survivalByQuantile("NDUFB5.TPM", survin, survin)

# Radiation
rad.mito <- survivalByQuantile("MitoScore.TPM", rad, rad)
rad.buffa <- survivalByQuantile("buffa.score.TPM", rad, rad)
rad.nduf <- survivalByQuantile("NDUFB5.TPM", rad, rad)

# IO
io.mito <- survivalByQuantile("MitoScore.TPM", io, io)
io.buffa <- survivalByQuantile("buffa.score.TPM", io, io)
io.nduf <- survivalByQuantile("NDUFB5.TPM", io, io)
```

# Plot

```{r}
plot_survival <- function(data, group, score) {
  ggplot(data, aes(x = percentile, y = -log(pval), color = hazard.direction, group = 1)) +
    geom_path() +
    geom_hline(yintercept = -log(0.05), linetype = "dashed", color = "gray") +
    labs(
      title = paste0("Group: ", toupper(group), " | Score: ", score),
      x = "Percentile",
      y = "-log(p-value)"
    ) +
    scale_color_manual(values = c("red", "black")) +
    theme_bw() +
    theme(plot.title = element_text(size = 10))
}

surv_results <- list(
  all.MitoScore = all.mito,
  all.BuffaScore = all.buffa,
  all.NDUFB5 = all.nduf,
  rad.MitoScore = rad.mito,
  rad.BuffaScore = rad.buffa,
  rad.NDUFB5 = rad.nduf,
  io.MitoScore = io.mito,
  io.BuffaScore = io.buffa,
  io.NDUFB5 = io.nduf
)

plots <- imap(surv_results, function(result, name) {
  parts <- strsplit(name, "\\.")[[1]]
  group <- parts[1]
  score <- parts[2]
  plot_survival(result, group, score)
})

combined_plot <- wrap_plots(plots, ncol = 3)

walk(plots, print)
print(combined_plot)

ggsave("../figures/mtsurv-exotho-2.png", combined_plot, height = 7, width = 10)
```

check function 





```{r}
input.var <- "buffa.score.TPM"
input.tax <- io
surv.dat <- io
percent <- 0.99


    surv.dat$input.var <- input.tax[[input.var]]
    cut <- quantile(surv.dat$input.var, percent)

    surv.dat$tmp <- case_when(surv.dat$input.var <= cut ~ 0,
                              surv.dat$input.var > cut ~ 1)
    surv.dat$tmp <- factor(surv.dat$tmp)
    surv.dat$tmp <- forcats::fct_relevel(surv.dat$tmp, "0")

    surv_model <- survival::coxph(survival::Surv(days, vitalstatus) ~ tmp, surv.dat)

    tidy_out <- broom::tidy(surv_model, exponentiate = TRUE, conf.int = TRUE)

    dat_temp <- tidy_out %>%
      dplyr::filter(term == "tmp1") %>%  # keep the comparison group (vs. reference "0")
      dplyr::mutate(
        percentile = percent,
        cutoff.value = cut,
        hazard.direction = ifelse(estimate >= 1, ">=1", "<1")
      ) %>%
      dplyr::select(
        hazard.ratio = estimate,
        low.bound = conf.low,
        upper.bound = conf.high,
        percentile,
        cutoff.value,
        pval = p.value,
        hazard.direction
      )

```



should I drop the middle tertile for the NDUFB5 analysis
```{r}
quantile(survin$NDUFB5.TPM, probs = c(1/3, 2/3), na.rm = TRUE)
survin <- survin %>%
  mutate(NDUFB5.tert = ifelse(NDUFB5.TPM < 42.45, "Low",
                              ifelse(NDUFB5.TPM >= 68.01, "High", NA)))
```


```{r}
#here is the 'drop the middle' code

test.quants <- seq(0.01, 0.5, by = 0.01)

tmp.out <- data.frame(i = test.quants,
                      hr = NA,
                      p.value = NA,
                      cutoff.value = NA)
i <- 1

for (i in 1:length(test.quants)) {
  
  lower.threshold <- test.quants[i]
  upper.threshold <- 1 - test.quants[i] 
  
  tmp <- 
    CApos %>% 
    mutate(new.groups = case_when(CandidaCount < quantile(CandidaCount, probs = lower.threshold) ~ "Low",
                                  CandidaCount > quantile(CandidaCount, probs = upper.threshold) ~ "High"))
  
  tmp.cand <- tmp %>% 
    select(AvatarKey, CandidaCount)
  
  survivaldfshort <- survivaldf %>% 
    right_join(tmp.cand, by = "AvatarKey") %>% 
    select(AvatarKey, diagsurvtime, vitalstatus, days)
    
  survoutput <-  mt.surv::survivalByQuantile("CandidaCount", tmp.cand, survivaldfshort)
  #need a left join and a select
  
  arranged.survoutput <- survoutput %>% 
  arrange(pval) 
  
  tmp.out$p.value[i] <- arranged.survoutput$pval[1]
  tmp.out$hr[i] <- arranged.survoutput$hazard.ratio[1]
  tmp.out$cutoff.value[i] <- arranged.survoutput$cutoff.value[1]
  
}

surv.dat$tmp <- case_when(surv.dat$input.var <= cut ~ 0,
                          surv.dat$input.var > cut ~ 1)
surv.dat$tmp <- case_when(surv.dat$input.var < cut ~ 0,
                          surv.dat$input.var >= cut ~ 1)
```

